import type { ProviderCatalogEntry } from "../catalog.js";

export const anthropicCatalog: ProviderCatalogEntry = {
  id: "anthropic",
  defaultModel: "claude-sonnet-5-5",
  models: [
    {
      id: "claude-sonnet-5-5",
      name: "claude-sonnet-5-5",
      contextWindow: 1000000,
      status: "current",
      capabilities: [
        "streaming",
        "tool-use",
        "vision",
        "anthropic-messages",
        "reasoning-effort",
        "adaptive-thinking",
      ],
      source: {
        name: "anthropic official documentation",
        url: "https://platform.claude.com/docs/en/models/overview",
        verifiedAt: "2026-10-07",
      },
      maxOutputTokens: 128000,
      reasoning: {
        kind: "effort",
        levels: ["low", "medium", "high", "xhigh", "max"],
        defaultMode: "high",
        mandatory: false,
      },
      pricing: {
        inputPerMillion: 2,
        outputPerMillion: 10,
      },
      recommended: true,
    },
    {
      id: "claude-opus-5-5",
      name: "claude-opus-5-5",
      contextWindow: 1000000,
      status: "current",
      capabilities: [
        "streaming",
        "tool-use",
        "vision",
        "anthropic-messages",
        "reasoning-effort",
        "adaptive-thinking",
      ],
      source: {
        name: "anthropic official documentation",
        url: "https://platform.claude.com/docs/en/models/overview",
        verifiedAt: "2026-10-07",
      },
      maxOutputTokens: 128000,
      reasoning: {
        kind: "effort",
        levels: ["low", "medium", "high", "xhigh", "max"],
        defaultMode: "medium",
        mandatory: true,
      },
      pricing: {
        inputPerMillion: 4,
        outputPerMillion: 20,
      },
    },
    {
      id: "claude-fable-5-1",
      name: "claude-fable-5-1",
      contextWindow: 1000000,
      status: "current",
      capabilities: [
        "streaming",
        "tool-use",
        "vision",
        "anthropic-messages",
        "reasoning-effort",
        "adaptive-thinking",
      ],
      source: {
        name: "anthropic official documentation",
        url: "https://platform.claude.com/docs/en/models/overview",
        verifiedAt: "2026-10-07",
      },
      maxOutputTokens: 128000,
      reasoning: {
        kind: "effort",
        levels: ["low", "medium", "high", "xhigh", "max"],
        defaultMode: "high",
        mandatory: true,
      },
      pricing: {
        inputPerMillion: 10,
        outputPerMillion: 50,
      },
    },
    {
      id: "claude-opus-4-8",
      name: "Claude Opus 4.8",
      description: "Most capable Opus-tier model for complex agentic work",
      contextWindow: 200000,
      maxOutputTokens: 128000,
      status: "current",
      capabilities: [
        "streaming",
        "tool-use",
        "vision",
        "adaptive-thinking",
        "reasoning-effort",
        "anthropic-messages",
      ],
      source: {
        name: "Anthropic models overview",
        url: "https://docs.anthropic.com/en/docs/about-claude/models/overview",
        verifiedAt: "2026-06-18",
      },
    },
    {
      id: "claude-sonnet-4-6",
      name: "Claude Sonnet 4.6",
      description: "Balanced default for coding, tool use, and long-running tasks",
      contextWindow: 200000,
      maxOutputTokens: 128000,
      status: "current",
      capabilities: [
        "streaming",
        "tool-use",
        "vision",
        "adaptive-thinking",
        "reasoning-effort",
        "anthropic-messages",
      ],
      pricing: {
        inputPerMillion: 3,
        outputPerMillion: 15,
      },
      source: {
        name: "Anthropic models overview",
        url: "https://docs.anthropic.com/en/docs/about-claude/models/overview",
        verifiedAt: "2026-06-18",
      },
    },
    {
      id: "claude-opus-4-6",
      name: "Claude Opus 4.6",
      description: "Legacy Opus option; prefer Opus 4.8 for new configurations",
      contextWindow: 200000,
      maxOutputTokens: 128000,
      status: "legacy",
      capabilities: [
        "streaming",
        "tool-use",
        "vision",
        "adaptive-thinking",
        "reasoning-effort",
        "anthropic-messages",
      ],
      pricing: {
        inputPerMillion: 5,
        outputPerMillion: 25,
      },
      source: {
        name: "Anthropic models overview",
        url: "https://docs.anthropic.com/en/docs/about-claude/models/overview",
        verifiedAt: "2026-06-18",
      },
    },
    {
      id: "claude-haiku-4-5-20251001",
      name: "Claude Haiku 4.5",
      description: "Fast low-cost Claude model",
      contextWindow: 200000,
      maxOutputTokens: 64000,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "anthropic-messages"],
      pricing: {
        inputPerMillion: 1,
        outputPerMillion: 5,
      },
      source: {
        name: "Anthropic models overview",
        url: "https://docs.anthropic.com/en/docs/about-claude/models/overview",
        verifiedAt: "2026-06-18",
      },
    },
    {
      id: "claude-haiku-5-5",
      name: "Claude Haiku 5.5",
      contextWindow: 1000000,
      status: "current",
      capabilities: [
        "streaming",
        "tool-use",
        "vision",
        "anthropic-messages",
        "reasoning-effort",
        "adaptive-thinking",
      ],
      source: {
        name: "anthropic official documentation",
        url: "https://platform.claude.com/docs/en/models/haiku-5-5/overview",
        verifiedAt: "2026-10-07",
      },
      maxOutputTokens: 128000,
      reasoning: {
        kind: "effort",
        levels: ["low", "medium", "high", "xhigh", "max"],
        defaultMode: "medium",
        mandatory: false,
      },
      pricing: {
        inputPerMillion: 0.1,
        outputPerMillion: 0.5,
        longContext: {
          threshold: 100000,
          inputPerMillion: 0.5,
          outputPerMillion: 2.5,
        },
      },
    },
  ],
};
