import type { ProviderCatalogEntry } from "../catalog.js";

export const codexCatalog: ProviderCatalogEntry = {
  id: "codex",
  defaultModel: "gpt-6.1-sol",
  models: [
    {
      id: "gpt-6.1-sol",
      name: "gpt-6.1-sol",
      contextWindow: 1050000,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "openai-responses", "reasoning-effort"],
      source: {
        name: "openai official documentation",
        url: "https://developers.openai.com/codex/models",
        verifiedAt: "2026-10-07",
      },
      maxOutputTokens: 128000,
      reasoning: {
        kind: "effort",
        levels: ["low", "medium", "high", "xhigh", "max"],
        defaultMode: "medium",
        mandatory: true,
      },
      availability: "account",
      recommended: true,
    },
    {
      id: "gpt-6-astra",
      name: "gpt-6-astra",
      contextWindow: 1050000,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "openai-responses", "reasoning-effort"],
      source: {
        name: "openai official documentation",
        url: "https://developers.openai.com/codex/models",
        verifiedAt: "2026-10-07",
      },
      maxOutputTokens: 128000,
      reasoning: {
        kind: "effort",
        levels: ["low", "medium", "high", "xhigh", "max"],
        defaultMode: "medium",
        mandatory: true,
      },
      availability: "account",
    },
    {
      id: "gpt-6-luna",
      name: "gpt-6-luna",
      contextWindow: 1050000,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "openai-responses", "reasoning-effort"],
      source: {
        name: "openai official documentation",
        url: "https://developers.openai.com/codex/models",
        verifiedAt: "2026-10-07",
      },
      maxOutputTokens: 128000,
      reasoning: {
        kind: "effort",
        levels: ["off", "low", "medium", "high", "xhigh", "max"],
        defaultMode: "medium",
        mandatory: false,
      },
      availability: "account",
    },
    {
      id: "gpt-5.5",
      name: "GPT-5.5",
      description: "Recommended Codex model for complex coding work",
      contextWindow: 1000000,
      maxOutputTokens: 128000,
      status: "current",
      capabilities: ["streaming", "tool-use", "reasoning-effort", "openai-responses"],
      source: {
        name: "OpenAI Codex models",
        url: "https://developers.openai.com/codex/models",
        verifiedAt: "2026-06-18",
      },
    },
    {
      id: "gpt-5.4-mini",
      name: "GPT-5.4 mini",
      description: "Faster Codex option for lighter work and subagents",
      contextWindow: 1000000,
      maxOutputTokens: 128000,
      status: "current",
      capabilities: ["streaming", "tool-use", "reasoning-effort", "openai-responses"],
      source: {
        name: "OpenAI Codex models",
        url: "https://developers.openai.com/codex/models",
        verifiedAt: "2026-06-18",
      },
    },
    {
      id: "gpt-5.3-codex-spark",
      name: "GPT-5.3 Codex Spark",
      description: "Research preview for near-instant coding iteration",
      contextWindow: 400000,
      maxOutputTokens: 128000,
      status: "experimental",
      capabilities: ["streaming", "tool-use", "reasoning-effort", "openai-responses"],
      source: {
        name: "OpenAI Codex models",
        url: "https://developers.openai.com/codex/models",
        verifiedAt: "2026-06-18",
      },
    },
  ],
};
