import type { ProviderCatalogEntry } from "../catalog.js";

export const copilotCatalog: ProviderCatalogEntry = {
  id: "copilot",
  defaultModel: "claude-sonnet-4.6",
  models: [
    {
      id: "gpt-6.1-sol",
      name: "gpt-6.1-sol",
      contextWindow: 168000,
      status: "current",
      availability: "account",
      capabilities: ["streaming", "tool-use", "openai-chat"],
      source: {
        name: "GitHub Copilot supported models",
        url: "https://docs.github.com/en/copilot/reference/ai-models/supported-models",
        verifiedAt: "2026-10-07",
      },
    },
    {
      id: "gpt-6-sol",
      name: "gpt-6-sol",
      contextWindow: 168000,
      status: "current",
      availability: "account",
      capabilities: ["streaming", "tool-use", "openai-chat"],
      source: {
        name: "GitHub Copilot supported models",
        url: "https://docs.github.com/en/copilot/reference/ai-models/supported-models",
        verifiedAt: "2026-10-07",
      },
    },
    {
      id: "gpt-6-luna",
      name: "gpt-6-luna",
      contextWindow: 168000,
      status: "current",
      availability: "account",
      capabilities: ["streaming", "tool-use", "openai-chat"],
      source: {
        name: "GitHub Copilot supported models",
        url: "https://docs.github.com/en/copilot/reference/ai-models/supported-models",
        verifiedAt: "2026-10-07",
      },
    },
    {
      id: "gpt-6-astra",
      name: "gpt-6-astra",
      contextWindow: 168000,
      status: "current",
      availability: "account",
      capabilities: ["streaming", "tool-use", "openai-chat"],
      source: {
        name: "GitHub Copilot supported models",
        url: "https://docs.github.com/en/copilot/reference/ai-models/supported-models",
        verifiedAt: "2026-10-07",
      },
    },
    {
      id: "gpt-5.6-sol",
      name: "gpt-5.6-sol",
      contextWindow: 168000,
      status: "current",
      availability: "account",
      capabilities: ["streaming", "tool-use", "openai-chat"],
      source: {
        name: "GitHub Copilot supported models",
        url: "https://docs.github.com/en/copilot/reference/ai-models/supported-models",
        verifiedAt: "2026-10-07",
      },
    },
    {
      id: "gpt-5.6-terra",
      name: "gpt-5.6-terra",
      contextWindow: 168000,
      status: "current",
      availability: "account",
      capabilities: ["streaming", "tool-use", "openai-chat"],
      source: {
        name: "GitHub Copilot supported models",
        url: "https://docs.github.com/en/copilot/reference/ai-models/supported-models",
        verifiedAt: "2026-10-07",
      },
    },
    {
      id: "gpt-5.6-luna",
      name: "gpt-5.6-luna",
      contextWindow: 168000,
      status: "current",
      availability: "account",
      capabilities: ["streaming", "tool-use", "openai-chat"],
      source: {
        name: "GitHub Copilot supported models",
        url: "https://docs.github.com/en/copilot/reference/ai-models/supported-models",
        verifiedAt: "2026-10-07",
      },
    },
    {
      id: "claude-sonnet-5.5",
      name: "claude-sonnet-5.5",
      contextWindow: 168000,
      status: "current",
      availability: "account",
      capabilities: ["streaming", "tool-use", "openai-chat"],
      source: {
        name: "GitHub Copilot supported models",
        url: "https://docs.github.com/en/copilot/reference/ai-models/supported-models",
        verifiedAt: "2026-10-07",
      },
    },
    {
      id: "claude-opus-5.5",
      name: "claude-opus-5.5",
      contextWindow: 168000,
      status: "current",
      availability: "account",
      capabilities: ["streaming", "tool-use", "openai-chat"],
      source: {
        name: "GitHub Copilot supported models",
        url: "https://docs.github.com/en/copilot/reference/ai-models/supported-models",
        verifiedAt: "2026-10-07",
      },
    },
    {
      id: "claude-fable-5.1",
      name: "claude-fable-5.1",
      contextWindow: 168000,
      status: "current",
      availability: "account",
      capabilities: ["streaming", "tool-use", "openai-chat"],
      source: {
        name: "GitHub Copilot supported models",
        url: "https://docs.github.com/en/copilot/reference/ai-models/supported-models",
        verifiedAt: "2026-10-07",
      },
    },
    {
      id: "gemini-3.8-flash",
      name: "gemini-3.8-flash",
      contextWindow: 168000,
      status: "current",
      availability: "account",
      capabilities: ["streaming", "tool-use", "openai-chat"],
      source: {
        name: "GitHub Copilot supported models",
        url: "https://docs.github.com/en/copilot/reference/ai-models/supported-models",
        verifiedAt: "2026-10-07",
      },
    },
    {
      id: "kimi-k3",
      name: "kimi-k3",
      contextWindow: 168000,
      status: "current",
      availability: "account",
      capabilities: ["streaming", "tool-use", "openai-chat"],
      source: {
        name: "GitHub Copilot supported models",
        url: "https://docs.github.com/en/copilot/reference/ai-models/supported-models",
        verifiedAt: "2026-10-07",
      },
    },
    {
      id: "grok-4.7",
      name: "grok-4.7",
      contextWindow: 168000,
      status: "current",
      availability: "account",
      capabilities: ["streaming", "tool-use", "openai-chat"],
      source: {
        name: "GitHub Copilot supported models",
        url: "https://docs.github.com/en/copilot/reference/ai-models/supported-models",
        verifiedAt: "2026-10-07",
      },
    },
    {
      id: "claude-sonnet-4.6",
      name: "Claude Sonnet 4.6",
      description: "Reliable Copilot default for coding and review",
      contextWindow: 168000,
      maxOutputTokens: 64000,
      recommended: true,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "openai-chat"],
      source: {
        name: "GitHub Copilot model comparison",
        url: "https://docs.github.com/en/copilot/reference/ai-models/model-comparison",
        verifiedAt: "2026-06-18",
      },
    },
    {
      id: "gpt-5.5",
      name: "GPT-5.5",
      description: "Copilot model for complex reasoning and technical decisions",
      contextWindow: 1000000,
      maxOutputTokens: 128000,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "openai-chat"],
      source: {
        name: "GitHub Copilot model comparison",
        url: "https://docs.github.com/en/copilot/reference/ai-models/model-comparison",
        verifiedAt: "2026-06-18",
      },
    },
    {
      id: "gpt-5.4",
      name: "GPT-5.4",
      description: "Copilot coding model",
      contextWindow: 1000000,
      maxOutputTokens: 128000,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "openai-chat"],
      source: {
        name: "GitHub Copilot supported models",
        url: "https://docs.github.com/copilot/reference/ai-models/supported-models",
        verifiedAt: "2026-06-18",
      },
    },
    {
      id: "gpt-5.4-mini",
      name: "GPT-5.4 mini",
      description: "Fast Copilot model for interactive coding",
      contextWindow: 1000000,
      maxOutputTokens: 128000,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "openai-chat"],
      source: {
        name: "GitHub Copilot supported models",
        url: "https://docs.github.com/copilot/reference/ai-models/supported-models",
        verifiedAt: "2026-06-18",
      },
    },
    {
      id: "gpt-5.3-codex",
      name: "GPT-5.3 Codex",
      description: "Copilot agentic coding model",
      contextWindow: 400000,
      maxOutputTokens: 128000,
      status: "current",
      capabilities: ["streaming", "tool-use", "openai-chat"],
      source: {
        name: "GitHub Copilot supported models",
        url: "https://docs.github.com/copilot/reference/ai-models/supported-models",
        verifiedAt: "2026-06-18",
      },
    },
    {
      id: "claude-opus-4.8",
      name: "Claude Opus 4.8",
      description: "Most capable Anthropic model exposed by Copilot when available",
      contextWindow: 168000,
      maxOutputTokens: 64000,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "openai-chat"],
      source: {
        name: "GitHub Copilot supported models",
        url: "https://docs.github.com/copilot/reference/ai-models/supported-models",
        verifiedAt: "2026-06-18",
      },
    },
    {
      id: "gemini-3.1-pro",
      name: "Gemini 3.1 Pro",
      description: "Gemini model exposed by Copilot",
      contextWindow: 1000000,
      maxOutputTokens: 64000,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "openai-chat"],
      source: {
        name: "GitHub Copilot supported models",
        url: "https://docs.github.com/copilot/reference/ai-models/supported-models",
        verifiedAt: "2026-06-18",
      },
    },
    {
      id: "gemini-3.5-flash",
      name: "Gemini 3.5 Flash",
      description: "Fast Gemini model exposed by Copilot",
      contextWindow: 1000000,
      maxOutputTokens: 64000,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "openai-chat"],
      source: {
        name: "GitHub Copilot supported models",
        url: "https://docs.github.com/copilot/reference/ai-models/supported-models",
        verifiedAt: "2026-06-18",
      },
    },
  ],
};
