import type { ProviderCatalogEntry } from "../catalog.js";

export const geminiCatalog: ProviderCatalogEntry = {
  id: "gemini",
  defaultModel: "gemini-3.8-flash",
  models: [
    {
      id: "gemini-3.7-flash",
      name: "gemini-3.7-flash",
      contextWindow: 1048576,
      status: "current",
      capabilities: [
        "streaming",
        "tool-use",
        "vision",
        "gemini-generate-content",
        "reasoning-effort",
      ],
      source: {
        name: "Official model documentation",
        url: "https://ai.google.dev/gemini-api/docs/models",
        verifiedAt: "2026-10-07",
      },
      maxOutputTokens: 65536,
      reasoning: {
        kind: "effort",
        levels: ["auto", "low", "medium", "high"],
        defaultMode: "auto",
        mandatory: true,
      },
    },
    {
      id: "gemini-3.6-flash",
      name: "gemini-3.6-flash",
      contextWindow: 1048576,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "gemini-generate-content"],
      source: {
        name: "Official model documentation",
        url: "https://ai.google.dev/gemini-api/docs/models",
        verifiedAt: "2026-10-07",
      },
      maxOutputTokens: 65536,
    },
    {
      id: "gemini-3.5-flash",
      name: "gemini-3.5-flash",
      contextWindow: 1048576,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "gemini-generate-content"],
      source: {
        name: "Official model documentation",
        url: "https://ai.google.dev/gemini-api/docs/models",
        verifiedAt: "2026-10-07",
      },
      maxOutputTokens: 65536,
    },
    {
      id: "gemini-3.1-flash-lite",
      name: "gemini-3.1-flash-lite",
      contextWindow: 1048576,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "gemini-generate-content"],
      source: {
        name: "Official model documentation",
        url: "https://ai.google.dev/gemini-api/docs/models",
        verifiedAt: "2026-10-07",
      },
      maxOutputTokens: 65536,
    },
    {
      id: "gemini-3.8-flash",
      name: "gemini-3.8-flash",
      contextWindow: 1048576,
      status: "current",
      capabilities: [
        "streaming",
        "tool-use",
        "vision",
        "gemini-generate-content",
        "reasoning-effort",
      ],
      source: {
        name: "gemini official documentation",
        url: "https://ai.google.dev/gemini-api/docs/models",
        verifiedAt: "2026-10-07",
      },
      maxOutputTokens: 65536,
      reasoning: {
        kind: "effort",
        levels: ["low", "medium", "high"],
        defaultMode: "auto",
        mandatory: true,
      },
      recommended: true,
    },
    {
      id: "gemini-3.5-flash-lite",
      name: "gemini-3.5-flash-lite",
      contextWindow: 1048576,
      status: "current",
      capabilities: [
        "streaming",
        "tool-use",
        "vision",
        "gemini-generate-content",
        "reasoning-effort",
      ],
      source: {
        name: "gemini official documentation",
        url: "https://ai.google.dev/gemini-api/docs/models",
        verifiedAt: "2026-10-07",
      },
      maxOutputTokens: 65536,
      reasoning: {
        kind: "effort",
        levels: ["low", "medium", "high"],
        defaultMode: "auto",
        mandatory: false,
      },
    },
    {
      id: "gemini-3.1-pro-preview",
      name: "Gemini 3.1 Pro Preview",
      description: "Most capable Gemini 3 model for agentic and coding workflows",
      contextWindow: 1000000,
      maxOutputTokens: 64000,
      status: "experimental",
      capabilities: [
        "streaming",
        "tool-use",
        "vision",
        "thinking-budget",
        "gemini-generate-content",
      ],
      source: {
        name: "Gemini 3 developer guide",
        url: "https://ai.google.dev/gemini-api/docs/gemini-3",
        verifiedAt: "2026-06-18",
      },
    },
    {
      id: "gemini-3-flash-preview",
      name: "Gemini 3 Flash Preview",
      description: "Fast Gemini 3 preview model",
      contextWindow: 1000000,
      maxOutputTokens: 64000,
      status: "experimental",
      capabilities: [
        "streaming",
        "tool-use",
        "vision",
        "thinking-budget",
        "gemini-generate-content",
      ],
      source: {
        name: "Gemini 3 developer guide",
        url: "https://ai.google.dev/gemini-api/docs/gemini-3",
        verifiedAt: "2026-06-18",
      },
    },
    {
      id: "gemini-2.5-pro",
      name: "Gemini 2.5 Pro",
      description: "Stable Gemini Pro model",
      contextWindow: 1048576,
      maxOutputTokens: 65536,
      status: "current",
      capabilities: [
        "streaming",
        "tool-use",
        "vision",
        "thinking-budget",
        "gemini-generate-content",
      ],
      source: {
        name: "Gemini API models",
        url: "https://ai.google.dev/gemini-api/docs/models",
        verifiedAt: "2026-06-18",
      },
      availability: "existing-users",
    },
    {
      id: "gemini-2.5-flash",
      name: "Gemini 2.5 Flash",
      description: "Stable fast Gemini model",
      contextWindow: 1048576,
      maxOutputTokens: 65536,
      status: "current",
      capabilities: [
        "streaming",
        "tool-use",
        "vision",
        "thinking-budget",
        "gemini-generate-content",
      ],
      source: {
        name: "Gemini API models",
        url: "https://ai.google.dev/gemini-api/docs/models",
        verifiedAt: "2026-06-18",
      },
      availability: "existing-users",
    },
    {
      id: "gemini-2.5-flash-lite",
      name: "Gemini 2.5 Flash-Lite",
      description: "Lowest-cost stable Gemini option",
      contextWindow: 1048576,
      maxOutputTokens: 65536,
      status: "current",
      capabilities: [
        "streaming",
        "tool-use",
        "vision",
        "thinking-budget",
        "gemini-generate-content",
      ],
      source: {
        name: "Gemini API models",
        url: "https://ai.google.dev/gemini-api/docs/models",
        verifiedAt: "2026-06-18",
      },
      availability: "existing-users",
    },
  ],
};
