import type { ProviderCatalogEntry } from "../catalog.js";

export const openaiCatalog: ProviderCatalogEntry = {
  id: "openai",
  defaultModel: "gpt-6.1-sol",
  models: [
    {
      id: "gpt-5.6-luna",
      name: "gpt-5.6-luna",
      contextWindow: 1050000,
      status: "current",
      capabilities: [
        "streaming",
        "tool-use",
        "openai-chat",
        "vision",
        "reasoning-effort",
        "openai-responses",
      ],
      source: {
        name: "OpenAI official model card",
        url: "https://developers.openai.com/api/docs/models/gpt-5.6-luna",
        verifiedAt: "2026-10-07",
      },
      reasoning: {
        kind: "effort",
        levels: ["off", "low", "medium", "high", "xhigh", "max"],
        defaultMode: "medium",
        mandatory: false,
      },
      pricing: {
        inputPerMillion: 0.2,
        outputPerMillion: 1.2,
        longContext: {
          threshold: 272000,
          inputPerMillion: 0.4,
          outputPerMillion: 1.7999999999999998,
        },
      },
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-6-sol",
      name: "gpt-6-sol",
      contextWindow: 1050000,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "openai-responses", "reasoning-effort"],
      source: {
        name: "OpenAI official model card",
        url: "https://developers.openai.com/api/docs/models/gpt-6-sol",
        verifiedAt: "2026-10-07",
      },
      maxOutputTokens: 128000,
      reasoning: {
        kind: "effort",
        levels: ["off", "low", "medium", "high", "xhigh", "max"],
        defaultMode: "medium",
        mandatory: false,
      },
      pricing: {
        inputPerMillion: 2,
        outputPerMillion: 10,
      },
    },
    {
      id: "gpt-5.6-sol",
      name: "gpt-5.6-sol",
      contextWindow: 1050000,
      status: "current",
      capabilities: [
        "streaming",
        "tool-use",
        "openai-chat",
        "vision",
        "reasoning-effort",
        "openai-responses",
      ],
      source: {
        name: "Official model documentation",
        url: "https://developers.openai.com/api/docs/models/gpt-5.6-sol",
        verifiedAt: "2026-10-07",
      },
      reasoning: {
        kind: "effort",
        levels: ["off", "low", "medium", "high", "xhigh", "max"],
        defaultMode: "medium",
        mandatory: false,
      },
      pricing: {
        inputPerMillion: 4,
        outputPerMillion: 20,
        longContext: {
          threshold: 272000,
          inputPerMillion: 8,
          outputPerMillion: 30.0,
        },
      },
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5.6-terra",
      name: "gpt-5.6-terra",
      contextWindow: 1050000,
      status: "current",
      capabilities: [
        "streaming",
        "tool-use",
        "openai-chat",
        "vision",
        "reasoning-effort",
        "openai-responses",
      ],
      source: {
        name: "Official model documentation",
        url: "https://developers.openai.com/api/docs/models/gpt-5.6-terra",
        verifiedAt: "2026-10-07",
      },
      reasoning: {
        kind: "effort",
        levels: ["off", "low", "medium", "high", "xhigh", "max"],
        defaultMode: "medium",
        mandatory: false,
      },
      pricing: {
        inputPerMillion: 2,
        outputPerMillion: 12,
        longContext: {
          threshold: 272000,
          inputPerMillion: 4,
          outputPerMillion: 18.0,
        },
      },
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-6.1-sol",
      name: "gpt-6.1-sol",
      contextWindow: 1050000,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "openai-responses", "reasoning-effort"],
      source: {
        name: "openai official documentation",
        url: "https://developers.openai.com/api/docs/models",
        verifiedAt: "2026-10-07",
      },
      maxOutputTokens: 128000,
      reasoning: {
        kind: "effort",
        levels: ["low", "medium", "high", "xhigh", "max"],
        defaultMode: "medium",
        mandatory: true,
      },
      pricing: {
        inputPerMillion: 2,
        outputPerMillion: 10,
      },
      recommended: true,
    },
    {
      id: "gpt-6-astra",
      name: "gpt-6-astra",
      contextWindow: 1050000,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "openai-responses", "reasoning-effort"],
      source: {
        name: "openai official documentation",
        url: "https://developers.openai.com/api/docs/models",
        verifiedAt: "2026-10-07",
      },
      maxOutputTokens: 128000,
      reasoning: {
        kind: "effort",
        levels: ["low", "medium", "high", "xhigh", "max"],
        defaultMode: "medium",
        mandatory: true,
      },
      pricing: {
        inputPerMillion: 10,
        outputPerMillion: 50,
      },
    },
    {
      id: "gpt-6-luna",
      name: "gpt-6-luna",
      contextWindow: 1050000,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "openai-responses", "reasoning-effort"],
      source: {
        name: "openai official documentation",
        url: "https://developers.openai.com/api/docs/models",
        verifiedAt: "2026-10-07",
      },
      maxOutputTokens: 128000,
      reasoning: {
        kind: "effort",
        levels: ["off", "low", "medium", "high", "xhigh", "max"],
        defaultMode: "medium",
        mandatory: false,
      },
      pricing: {
        inputPerMillion: 0.1,
        outputPerMillion: 0.5,
      },
    },
    {
      id: "gpt-5.5",
      name: "GPT-5.5",
      description: "Default for complex coding, agentic workflows, and tool-heavy tasks",
      contextWindow: 1000000,
      maxOutputTokens: 128000,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "reasoning-effort", "openai-responses"],
      pricing: {
        inputPerMillion: 5,
        outputPerMillion: 30,
      },
      source: {
        name: "OpenAI models",
        url: "https://developers.openai.com/api/docs/models",
        verifiedAt: "2026-06-18",
      },
    },
    {
      id: "gpt-5.4",
      name: "GPT-5.4",
      description: "Affordable model for coding and professional work",
      contextWindow: 1000000,
      maxOutputTokens: 128000,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "reasoning-effort", "openai-responses"],
      source: {
        name: "OpenAI all models",
        url: "https://developers.openai.com/api/docs/models/all",
        verifiedAt: "2026-06-18",
      },
    },
    {
      id: "gpt-5.4-mini",
      name: "GPT-5.4 mini",
      description: "Fast model for lighter coding tasks and subagents",
      contextWindow: 1000000,
      maxOutputTokens: 128000,
      status: "current",
      capabilities: ["streaming", "tool-use", "vision", "reasoning-effort", "openai-responses"],
      source: {
        name: "OpenAI all models",
        url: "https://developers.openai.com/api/docs/models/all",
        verifiedAt: "2026-06-18",
      },
    },
    {
      id: "gpt-5.3-codex",
      name: "GPT-5.3 Codex",
      description: "Agentic coding model; keep separate from older ChatGPT-only aliases",
      contextWindow: 400000,
      maxOutputTokens: 128000,
      status: "current",
      capabilities: ["streaming", "tool-use", "reasoning-effort", "openai-responses"],
      source: {
        name: "OpenAI all models",
        url: "https://developers.openai.com/api/docs/models/all",
        verifiedAt: "2026-06-18",
      },
    },
    {
      id: "gpt-4.1",
      name: "GPT-4.1",
      description: "Legacy long-context non-reasoning model",
      contextWindow: 1047576,
      maxOutputTokens: 32768,
      status: "legacy",
      capabilities: ["streaming", "tool-use", "vision", "openai-chat"],
      pricing: {
        inputPerMillion: 2,
        outputPerMillion: 8,
      },
      source: {
        name: "OpenAI all models",
        url: "https://developers.openai.com/api/docs/models/all",
        verifiedAt: "2026-06-18",
      },
    },
  ],
};
