export const PROVIDER_IDS = [
  "anthropic",
  "openai",
  "codex",
  "copilot",
  "gemini",
  "vertex",
  "kimi",
  "kimi-code",
  "lmstudio",
  "ollama",
  "groq",
  "openrouter",
  "mistral",
  "deepseek",
  "together",
  "huggingface",
  "qwen",
  "xai",
  "minimax",
  "cerebras",
  "azure-openai",
  "bedrock",
] as const;
export type ProviderType = (typeof PROVIDER_IDS)[number];
