/**
 * Tests for the commit message module
 */

import { describe, it, expect } from "vitest";
import { sanitizeCommitMessage, formatCommitMessage, inferCommitType } from "./commit-message.js";

describe("sanitizeCommitMessage", () => {
  it("removes Co-authored-by lines", () => {
    const msg = `feat: add feature

Co-authored-by: Claude <noreply@anthropic.com>`;
    expect(sanitizeCommitMessage(msg)).toBe("feat: add feature");
  });

  it("removes co-authored-by case-insensitively", () => {
    const msg = `fix: bug fix

co-authored-by: GPT-4 <noreply@openai.com>
CO-AUTHORED-BY: Copilot <noreply@github.com>`;
    expect(sanitizeCommitMessage(msg)).toBe("fix: bug fix");
  });

  it("removes generated by/with lines", () => {
    const msg = `feat: new feature

Generated with Claude Code
Generated by AI assistant`;
    expect(sanitizeCommitMessage(msg)).toBe("feat: new feature");
  });

  it("removes robot emoji lines", () => {
    const msg = `feat: feature
🤖 This was generated by AI`;
    expect(sanitizeCommitMessage(msg)).toBe("feat: feature");
  });

  it("preserves normal commit messages", () => {
    const msg = `feat(auth): add oauth support

- Added OAuth2 flow
- Updated configuration
- Added tests`;
    expect(sanitizeCommitMessage(msg)).toBe(msg);
  });

  it("collapses multiple blank lines", () => {
    const msg = `feat: feature



body here`;
    expect(sanitizeCommitMessage(msg)).toBe("feat: feature\n\nbody here");
  });

  it("handles empty string", () => {
    expect(sanitizeCommitMessage("")).toBe("");
  });

  it("removes AI-assisted attribution", () => {
    const msg = `fix: something

[claude] assisted this commit`;
    expect(sanitizeCommitMessage(msg)).toBe("fix: something");
  });
});

describe("formatCommitMessage", () => {
  it("formats a simple commit", () => {
    const result = formatCommitMessage({
      type: "feat",
      description: "add new feature",
    });
    expect(result).toBe("feat: add new feature");
  });

  it("formats with scope", () => {
    const result = formatCommitMessage({
      type: "fix",
      scope: "auth",
      description: "resolve login bug",
    });
    expect(result).toBe("fix(auth): resolve login bug");
  });

  it("formats with bullets", () => {
    const result = formatCommitMessage({
      type: "feat",
      description: "add features",
      bullets: ["Added X", "Updated Y"],
    });
    expect(result).toContain("feat: add features");
    expect(result).toContain("- Added X");
    expect(result).toContain("- Updated Y");
  });

  it("formats breaking change", () => {
    const result = formatCommitMessage({
      type: "feat",
      description: "new api",
      breaking: true,
    });
    expect(result).toContain("feat!: new api");
    expect(result).toContain("BREAKING CHANGE");
  });
});

describe("inferCommitType", () => {
  it("infers docs for documentation-only changes", () => {
    const result = inferCommitType(["docs/README.md", "CHANGELOG.md"]);
    expect(result.type).toBe("docs");
  });

  it("infers test for test-only changes", () => {
    const result = inferCommitType(["src/auth.test.ts", "src/user.spec.ts"]);
    expect(result.type).toBe("test");
  });

  it("infers ci for CI-only changes", () => {
    const result = inferCommitType([".github/workflows/ci.yml"]);
    expect(result.type).toBe("ci");
  });

  it("infers feat for source + test changes", () => {
    const result = inferCommitType(["src/feature.ts", "src/feature.test.ts"]);
    expect(result.type).toBe("feat");
  });

  it("infers chore for config-only changes", () => {
    const result = inferCommitType(["tsconfig.json", "package.json"]);
    expect(result.type).toBe("chore");
  });
});
