/**
 * Tests for diff-formatter utility
 */

import { describe, it, expect } from "vitest";
import {
  formatChangeSummary,
  formatDiff,
  isAutoGenerated,
  filterAutoGenerated,
} from "./diff-formatter.js";

// Mock chalk
vi.mock("chalk", () => {
  const mockFn = (s: string) => s;
  const mockBold = (s: string) => s;
  mockFn.bold = mockBold;
  
  return {
    default: {
      dim: mockFn,
      cyan: Object.assign(mockFn, { bold: mockBold }),
      green: mockFn,
      red: mockFn,
      yellow: mockFn,
      bold: mockBold,
      gray: mockFn,
      white: Object.assign(mockFn, { bold: mockBold }),
      magenta: { bold: mockBold },
    },
  };
});

import { vi } from "vitest";

describe("diff-formatter", () => {
  describe("formatChangeSummary", () => {
    it("should format summary of changes", () => {
      const files = [
        { path: "file1.ts", additions: 10, deletions: 5, status: "modified" as const },
        { path: "file2.ts", additions: 20, deletions: 0, status: "added" as const },
      ];

      const result = formatChangeSummary(files);

      expect(result).toContain("Changed files (2)");
      expect(result).toContain("file1.ts");
      expect(result).toContain("file2.ts");
      expect(result).toContain("+30 / -5");
    });

    it("should return message when no files", () => {
      const result = formatChangeSummary([]);

      expect(result).toContain("No changes");
    });

    it("should respect maxFiles option", () => {
      const files = Array.from({ length: 15 }, (_, i) => ({
        path: `file${i}.ts`,
        additions: 1,
        deletions: 0,
        status: "modified" as const,
      }));

      const result = formatChangeSummary(files, { maxFiles: 5 });

      expect(result).toContain("and 10 more files");
    });
  });

  describe("formatDiff", () => {
    it("should format diff with syntax highlighting", () => {
      const diff = `diff --git a/file.ts b/file.ts
index abc..def 100644
--- a/file.ts
+++ b/file.ts
@@ -1,3 +1,4 @@
+added line
 existing line
-removed line`;

      const result = formatDiff(diff);

      expect(result).toContain("added line");
      expect(result).toContain("removed line");
    });

    it("should truncate long diffs", () => {
      const diff = Array(100).fill("+line").join("\n");

      const result = formatDiff(diff, { maxLinesPerFile: 10 });

      expect(result).toContain("more lines");
    });

    it("should return message for empty diff", () => {
      const result = formatDiff("");

      expect(result).toContain("No diff");
    });
  });

  describe("isAutoGenerated", () => {
    it("should detect package-lock.json", () => {
      expect(isAutoGenerated("package-lock.json")).toBe(true);
      expect(isAutoGenerated("/path/to/package-lock.json")).toBe(true);
    });

    it("should detect yarn.lock", () => {
      expect(isAutoGenerated("yarn.lock")).toBe(true);
    });

    it("should detect pnpm-lock.yaml", () => {
      expect(isAutoGenerated("pnpm-lock.yaml")).toBe(true);
    });

    it("should detect minified files", () => {
      expect(isAutoGenerated("app.min.js")).toBe(true);
      expect(isAutoGenerated("styles.min.css")).toBe(true);
    });

    it("should detect dist/build folders", () => {
      expect(isAutoGenerated("dist/bundle.js")).toBe(true);
      expect(isAutoGenerated("build/output.js")).toBe(true);
    });

    it("should not flag regular source files", () => {
      expect(isAutoGenerated("src/index.ts")).toBe(false);
      expect(isAutoGenerated("app.ts")).toBe(false);
      expect(isAutoGenerated("README.md")).toBe(false);
    });
  });

  describe("filterAutoGenerated", () => {
    it("should filter out auto-generated files", () => {
      const files = [
        { path: "package-lock.json", additions: 100, deletions: 50, status: "modified" as const },
        { path: "src/index.ts", additions: 10, deletions: 5, status: "modified" as const },
        { path: "dist/bundle.js", additions: 1000, deletions: 0, status: "added" as const },
        { path: "app.ts", additions: 5, deletions: 2, status: "modified" as const },
      ];

      const result = filterAutoGenerated(files);

      expect(result).toHaveLength(2);
      expect(result.map((f) => f.path)).toEqual(["src/index.ts", "app.ts"]);
    });

    it("should return empty array when all files are auto-generated", () => {
      const files = [
        { path: "package-lock.json", additions: 100, deletions: 50, status: "modified" as const },
        { path: "yarn.lock", additions: 200, deletions: 100, status: "modified" as const },
      ];

      const result = filterAutoGenerated(files);

      expect(result).toEqual([]);
    });
  });
});
