/**
 * GitHub Actions — Quality Workflow Generator
 *
 * Generates a `.github/workflows/quality.yml` that runs `coco check` on every
 * push and pull-request, then optionally posts the results as a PR comment.
 *
 * Also provides `formatQualityPRComment()` for posting rich Markdown comments
 * on GitHub PRs via the GitHub API or `gh pr comment`.
 *
 * Usage:
 *   const yaml = generateQualityWorkflow({ commentOnPR: true });
 *   await writeFile(".github/workflows/quality.yml", yaml);
 *
 *   // In CI, after running coco:
 *   const comment = formatQualityPRComment(evaluation, { repoUrl });
 *   // post with: gh pr comment $PR --body "$comment"
 */

import type { QualityEvaluation } from "../../quality/types.js";
import { DIMENSION_LABELS, DIMENSION_ORDER } from "../../quality/dimension-constants.js";

// ──────────────────────────────────────────────────────────────────────────────
// Workflow generation
// ──────────────────────────────────────────────────────────────────────────────

export interface QualityWorkflowOptions {
  /** Node.js version to use in CI. Default: "22" */
  nodeVersion?: string;
  /** Package manager. Default: "pnpm" */
  packageManager?: "pnpm" | "npm" | "yarn";
  /** Fail the workflow when quality is below minimum. Default: true */
  failOnBelowMinimum?: boolean;
  /** Post results as a PR comment. Default: true */
  commentOnPR?: boolean;
  /** Branches that trigger the workflow. Default: ["main", "master"] */
  branches?: string[];
}

/**
 * Generate the content of `.github/workflows/quality.yml`.
 * The resulting YAML installs dependencies, runs `pnpm coco check` (or npm
 * equivalent), saves the JSON report as an artifact, and optionally posts a
 * summary as a PR comment.
 */
export function generateQualityWorkflow(options: QualityWorkflowOptions = {}): string {
  const {
    nodeVersion = "22",
    packageManager = "pnpm",
    failOnBelowMinimum = true,
    commentOnPR = true,
    branches = ["main", "master"],
  } = options;

  const installCmd =
    packageManager === "pnpm"
      ? "pnpm install --frozen-lockfile"
      : packageManager === "yarn"
        ? "yarn install --frozen-lockfile"
        : "npm ci";

  const checkCmd =
    packageManager === "pnpm"
      ? "pnpm coco check --output json --output-file .coco/reports/quality.json"
      : packageManager === "yarn"
        ? "yarn coco check --output json --output-file .coco/reports/quality.json"
        : "npx coco check --output json --output-file .coco/reports/quality.json";

  const branchList = branches.map((b) => `          - ${b}`).join("\n");

  const pnpmSetup =
    packageManager === "pnpm"
      ? `
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
`
      : "";

  const commentStep = commentOnPR
    ? `
      - name: Post quality report as PR comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            // Note: This is embedded JS for actions/github-script which runs in CommonJS context
            const fs = require('fs');
            const report = JSON.parse(fs.readFileSync('.coco/reports/quality.json', 'utf8'));
            const score = Math.round(report.scores.overall);
            const status = report.meetsMinimum ? '✅ PASS' : '❌ FAIL';
            const body = \`## Quality Report — \${status}\\n\\n**Overall score: \${score}/100**\\n\\n> Generated by Corbat-Coco\`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });
`
    : "";

  const continueOnError = failOnBelowMinimum ? "" : "\n        continue-on-error: true";

  return `name: Quality Check

on:
  push:
    branches:
${branchList}
  pull_request:
    branches:
${branchList}

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
${pnpmSetup}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${nodeVersion}"
          cache: "${packageManager}"

      - name: Install dependencies
        run: ${installCmd}

      - name: Run quality check
        run: ${checkCmd}${continueOnError}

      - name: Upload quality report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: quality-report
          path: .coco/reports/quality.json
          retention-days: 30
${commentStep}`;
}

// ──────────────────────────────────────────────────────────────────────────────
// PR comment formatting
// ──────────────────────────────────────────────────────────────────────────────

export interface PRCommentOptions {
  /** Repository URL for deep-linking. Optional. */
  repoUrl?: string;
  /** Show per-dimension breakdown. Default: true */
  showDimensions?: boolean;
  /** Show top issues. Default: true */
  showIssues?: boolean;
  /** Maximum issues to display. Default: 5 */
  maxIssues?: number;
}


/**
 * Format a `QualityEvaluation` as a Markdown string suitable for posting as a
 * GitHub PR comment.
 */
export function formatQualityPRComment(
  evaluation: QualityEvaluation,
  options: PRCommentOptions = {},
): string {
  const { showDimensions = true, showIssues = true, maxIssues = 5 } = options;

  const overall = Math.round(evaluation.scores.overall);
  const statusBadge = evaluation.meetsMinimum ? "✅ PASS" : "❌ FAIL";
  const evaluatedAt = evaluation.scores.evaluatedAt.toISOString().slice(0, 10);

  const lines: string[] = [
    `## Quality Check — ${statusBadge}`,
    ``,
    `**Overall score:** \`${overall}/100\` &nbsp; | &nbsp; **Evaluated:** ${evaluatedAt}`,
    ``,
  ];

  if (showDimensions) {
    lines.push(`<details>`);
    lines.push(`<summary>📊 Dimension breakdown</summary>`);
    lines.push(``);
    lines.push(`| Dimension | Score | Status |`);
    lines.push(`|-----------|------:|--------|`);

    for (const key of DIMENSION_ORDER) {
      const score = Math.round(evaluation.scores.dimensions[key] ?? 0);
      const icon = score >= 90 ? "✅" : score >= 75 ? "⚠️" : "❌";
      lines.push(`| ${DIMENSION_LABELS[key]} | ${score} | ${icon} |`);
    }

    lines.push(``);
    lines.push(`</details>`);
    lines.push(``);
  }

  if (showIssues && evaluation.issues.length > 0) {
    const shown = evaluation.issues.slice(0, maxIssues);
    const remaining = evaluation.issues.length - shown.length;
    lines.push(`<details>`);
    lines.push(`<summary>🔍 Issues (${evaluation.issues.length})</summary>`);
    lines.push(``);
    for (const issue of shown) {
      const sev =
        issue.severity === "critical" ? "🔴" : issue.severity === "major" ? "🟡" : "🔵";
      lines.push(`- ${sev} **[${issue.dimension}]** ${issue.message}`);
    }
    if (remaining > 0) {
      lines.push(`- _… and ${remaining} more_`);
    }
    lines.push(``);
    lines.push(`</details>`);
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`_🥥 Generated by [Corbat-Coco](https://github.com/corbat-tech/coco)_`);

  return lines.join("\n");
}
