/**
 * /diff command - Show diff of uncommitted changes
 * Inspired by Codex CLI: concise, relevant, no noise
 */

import type { ReplSession, SlashCommand } from "../types.js";
import {
  formatFullDiff,
  formatChangeSummary,
  getModifiedFiles,
  getStagedFiles,
  hasUncommittedChanges,
  getQuickChangeSummary,
  filterAutoGenerated,
} from "../../../utils/diff-formatter.js";
import chalk from "chalk";

/**
 * Diff command options
 */
export interface DiffCommandOptions {
  /** Show only summary without file contents */
  summary?: boolean;
  /** Show all files (ignore maxFiles limit) */
  all?: boolean;
  /** Show staged changes only */
  staged?: boolean;
  /** Show unstaged changes only */
  unstaged?: boolean;
  /** Filter out auto-generated files */
  noGenerated?: boolean;
}

/**
 * Execute the diff command
 */
export async function executeDiffCommand(
  session: ReplSession,
  args: string[],
): Promise<string> {
  const options = parseArgs(args);
  const cwd = session.projectPath;

  // Check if there are any changes
  if (!hasUncommittedChanges(cwd)) {
    return chalk.gray("✓ No uncommitted changes.");
  }

  // Determine which files to show
  let files = options.staged
    ? getStagedFiles(cwd)
    : options.unstaged
      ? getModifiedFiles(cwd)
      : [...getStagedFiles(cwd), ...getModifiedFiles(cwd)];

  // Filter auto-generated files if requested
  if (options.noGenerated) {
    files = filterAutoGenerated(files);
  }

  if (files.length === 0) {
    return chalk.gray("✓ No changes to display (after filtering).");
  }

  // Show summary only
  if (options.summary) {
    return formatChangeSummary(files, { maxFiles: options.all ? 0 : 10 });
  }

  // Show full diff
  return formatFullDiff(cwd, {
    maxFiles: options.all ? 0 : 5,
    maxLinesPerFile: options.all ? 0 : 50,
    summaryOnly: false,
  }, files);
}

/**
 * Parse command arguments
 */
function parseArgs(args: string[]): DiffCommandOptions {
  return {
    summary: args.includes("--summary") || args.includes("-s"),
    all: args.includes("--all") || args.includes("-a"),
    staged: args.includes("--staged") || args.includes("-c"),
    unstaged: args.includes("--unstaged") || args.includes("-u"),
    noGenerated: args.includes("--no-generated") || args.includes("-G"),
  };
}

/**
 * Get help text for the diff command
 */
export function getDiffHelp(): string {
  return `
${chalk.bold("/diff")} - Show uncommitted changes

${chalk.bold("Usage:")}
  /diff              Show diff of all uncommitted changes
  /diff --summary    Show only file list with stats
  /diff --staged     Show only staged changes
  /diff --unstaged   Show only unstaged changes
  /diff --all        Show all files without limits
  /diff --no-generated  Filter out auto-generated files

${chalk.bold("Aliases:")}
  -s, --summary
  -a, --all
  -c, --staged (cached)
  -u, --unstaged
  -G, --no-generated

${chalk.bold("Examples:")}
  /diff              # Quick overview of changes
  /diff --summary    # Just the file list
  /diff --all        # Complete diff without truncation
`;
}

/**
 * Quick diff summary for display after operations
 */
export function getQuickDiffSummary(cwd?: string): string {
  if (!hasUncommittedChanges(cwd)) {
    return "";
  }

  return getQuickChangeSummary(cwd);
}

/**
 * Slash command definition for /diff
 */
export const diffCommand: SlashCommand = {
  name: "diff",
  aliases: ["d"],
  description: "Show git diff of changes",
  usage: "/diff [--summary|--staged|--unstaged|--all|--no-generated]",

  async execute(args: string[], session: ReplSession): Promise<boolean> {
    const output = await executeDiffCommand(session, args);
    console.log(output);
    return false;
  },
};
