/**
 * Corbat-Coco: Autonomous Coding Agent
 *
 * An autonomous coding agent with self-review, quality convergence,
 * and production-ready output following the COCO methodology:
 * CONVERGE → ORCHESTRATE → COMPLETE → OUTPUT
 *
 * @packageDocumentation
 */

// Version
export { VERSION } from "./version.js";

// Orchestrator
export { createOrchestrator } from "./orchestrator/index.js";
export type {
  Orchestrator,
  OrchestratorConfig,
  ProjectState,
  Progress,
} from "./orchestrator/types.js";

// Configuration
export { loadConfig, saveConfig, createDefaultConfig, configExists } from "./config/index.js";
export type { CocoConfig } from "./config/index.js";

// Phases - Core types
export type { Phase, PhaseResult, PhaseExecutor, PhaseContext } from "./phases/types.js";

// Phases - CONVERGE
export {
  DiscoveryEngine,
  createDiscoveryEngine,
  SpecificationGenerator,
  createSpecificationGenerator,
  SessionManager,
  createSessionManager,
  ConvergeExecutor,
  createConvergeExecutor,
} from "./phases/converge/index.js";

// Phases - ORCHESTRATE
export {
  ArchitectureGenerator,
  createArchitectureGenerator,
  ADRGenerator,
  createADRGenerator,
  BacklogGenerator,
  createBacklogGenerator,
  OrchestrateExecutor,
  createOrchestrateExecutor,
} from "./phases/orchestrate/index.js";

// Phases - COMPLETE
export {
  CodeGenerator,
  createCodeGenerator,
  CodeReviewer,
  createCodeReviewer,
  TaskIterator,
  createTaskIterator,
  CompleteExecutor,
  createCompleteExecutor,
} from "./phases/complete/index.js";

// Phases - OUTPUT
export {
  CICDGenerator,
  createCICDGenerator,
  DockerGenerator,
  createDockerGenerator,
  DocsGenerator,
  createDocsGenerator,
  OutputExecutor,
  createOutputExecutor,
} from "./phases/output/index.js";

// Quality
export type { QualityScores, QualityDimensions, QualityThresholds } from "./quality/types.js";

// Tasks
export type { Task, TaskVersion, TaskHistory, Sprint, Story, Epic, Backlog } from "./types/task.js";

// Providers
export { AnthropicProvider, createAnthropicProvider, createProvider } from "./providers/index.js";
export type { LLMProvider, Message, ChatResponse, ChatOptions } from "./providers/types.js";

// Reusable agent runtime
export {
  AgentRuntime,
  AgentRunner,
  AGENT_MODES,
  DefaultRuntimeTurnRunner,
  ToolCallingRuntimeTurnRunner,
  ProviderRegistry,
  InMemoryEventLog,
  InMemoryRuntimeSessionStore,
  FileRuntimeSessionStore,
  DefaultPermissionPolicy,
  FileEventLog,
  AsyncPostgresEventLog,
  AsyncPostgresRuntimeSessionStore,
  createAgentRuntime,
  createAgentRunner,
  createDefaultRuntimeTurnRunner,
  createToolCallingRuntimeTurnRunner,
  getAgentMode,
  isAgentMode,
  listAgentModes,
  createProviderRegistry,
  createEventLog,
  createFileRuntimeSessionStore,
  createFileEventLog,
  createAsyncPostgresEventLog,
  createAsyncPostgresRuntimeSessionStore,
  createPostgresRuntimeAuditStore,
  createRuntimeHttpServer,
  createRuntimeSessionStore,
  createPermissionPolicy,
  createMcpToolPolicy,
  assertRuntimeTenantBoundary,
  assertRuntimeTurnWithinPolicy,
  createRetentionCutoffs,
  createRuntimeRequestContext,
  createRuntimeTenantBoundary,
  mergeRuntimePolicy,
  RuntimePolicyViolation,
  runtimeContextToMetadata,
  createAgentFromBlueprint,
  createBaseBlueprint,
  createSafeToolRegistry,
  mapActionModeToRuntimeMode,
  defaultPublicGuardrails,
  redactSecrets,
  runGuardrails,
  validateStructuredOutput,
  createInMemoryKnowledgeRetriever,
  createInMemoryVectorStore,
  createRagPipeline,
  createSimpleTextChunker,
  formatRetrievedSourcesForPrompt,
  InMemoryKnowledgeRetriever,
  InMemoryVectorStore,
  SimpleTextChunker,
  createRuntimeToolExecutor,
  createTenantScopedEventLog,
  createTenantScopedRuntimeSessionStore,
  createWorkflowCatalog,
  createWorkflowEngine,
  createWorkflowRegistry,
  createAgentArtifact,
  createAgentGraphEngine,
  createAgentTraceContext,
  createSummaryArtifact,
  dryRunAgentGraphNodeExecutor,
  evaluateAgentToolPolicy,
  FileSharedWorkspaceStore,
  InMemorySharedWorkspaceStore,
  listLegacyAgentRoleMappings,
  mapLegacyAgentRole,
  DEFAULT_WORKFLOWS,
  normalizeAgentRunResult,
  AgentGraphEngine,
  RuntimeToolExecutor,
  PostgresRuntimeAuditStore,
  TenantScopedEventLog,
  TenantScopedRuntimeSessionStore,
  SharedWorkspaceState,
  validateAgentCapabilities,
  validateAgentGraph,
  workflowToAgentGraph,
  WorkflowCatalog,
  WorkflowEngine,
  WorkflowRegistry,
  type RuntimeRetentionCleanupOptions,
  type RuntimeRetentionCleanupResult,
  type ToolCallingRuntimeTurnRunnerOptions,
} from "./runtime/index.js";
export type {
  AgentModeDefinition,
  AgentModeId,
  AgentActionMode,
  AgentArtifact,
  AgentArtifactKind,
  AgentBudget,
  AgentBlueprint,
  AgentCapability,
  AgentCard,
  AgentDefinition,
  AgentDeploymentSurface,
  AgentGateDefinition,
  AgentGateKind,
  AgentGraphDefinition,
  AgentGraphEdge,
  AgentGraphEngineOptions,
  AgentGraphNode,
  AgentGraphNodeExecution,
  AgentGraphNodeExecutor,
  AgentGraphRunInput,
  AgentGraphRunResult,
  AgentGraphRunStatus,
  AgentGraphValidationIssue,
  AgentGraphValidationResult,
  AgentGuardrailPolicy,
  AgentHandoff,
  AgentMessage,
  AgentMessageRole,
  AgentMaturity,
  AgentPreset,
  AgentRole,
  AgentRunResult,
  AgentRunStatus,
  AgentRuntimeFactoryOptions,
  AgentRuntimeOptions,
  AgentRuntimeSnapshot,
  AsyncEventLog,
  AsyncRuntimeSessionStore,
  AgentRunnerExecutionContext,
  AgentRunnerExecutionInput,
  AgentRunnerExecutor,
  AgentRunnerOptions,
  AgentRunnerRawResult,
  ApprovalPolicy,
  BlueprintAgent,
  Chunker,
  Citation,
  CostBudget,
  DataBoundary,
  DocumentLoader,
  EmbeddingProvider,
  EventLog,
  GuardrailConfig,
  GuardrailFinding,
  GuardrailResult,
  GuardrailSeverity,
  GuardrailStage,
  InMemoryKnowledgeDocument,
  KnowledgeRetriever,
  MemoryConfig,
  ObservabilityConfig,
  PermissionDecision,
  PermissionPolicy,
  ProviderRuntimeSelection,
  ReasoningEffort,
  RetentionPolicy,
  RagChunk,
  RagDocument,
  RagPipeline,
  RagPipelineOptions,
  Reranker,
  RetrievedSource,
  RetrievalOptions,
  RuntimeEvent,
  RuntimeEventType,
  RuntimeHostMode,
  RuntimeMode,
  RuntimePolicy,
  RuntimePolicyViolationCode,
  RuntimeRequestContext,
  RuntimeSurface,
  RuntimeTenantBoundary,
  RuntimeHttpServerOptions,
  RuntimeAuditRecord,
  RuntimeAuditStore,
  RuntimeSession,
  RuntimeSessionCreateOptions,
  RuntimeSessionStore,
  RuntimeToolExecutionInput,
  RuntimeToolExecutionResult,
  RuntimeToolExecutorInput,
  RuntimeToolExecutorOptions,
  RuntimeTurnContext,
  RuntimeTurnInput,
  RuntimeTurnResult,
  RuntimeTurnStreamEvent,
  RuntimeTurnRunner,
  SecretRedactionConfig,
  TenantContext,
  TopicBoundaryConfig,
  UserContext,
  VectorStore,
  AgentSurface,
  AgentToolPolicyDecision,
  AgentTraceContext,
  ExtensionRisk,
  LegacyAgentRoleMapping,
  McpToolPolicy,
  RecipeManifest,
  RecipeStep,
  SkillManifest,
  SharedWorkspaceProvenance,
  SharedWorkspaceRecord,
  SharedWorkspaceRecordKind,
  SharedWorkspaceStore,
  SharedWorkspaceStateSnapshot,
  SharedWorkspaceWriteInput,
  ToolRiskLevel,
  ToolRiskManifest,
  ToolRiskManifestEntry,
  AgentTask as RuntimeAgentTask,
  WorkflowDefinition,
  WorkflowHandler,
  WorkflowPlan,
  WorkflowRetryPolicy,
  WorkflowRunContext,
  WorkflowRunInput,
  WorkflowRunResult,
  WorkflowRunStatus,
  WorkflowRisk,
  WorkflowStepDefinition,
} from "./runtime/index.js";

// Tools
export {
  ToolRegistry,
  createToolRegistry,
  registerAllTools,
  createFullToolRegistry,
} from "./tools/index.js";
export {
  createCodingToolRegistry,
  createCustomerSupportToolRegistry,
  createNoToolRegistry,
  createPublicWebToolRegistry,
  createRagToolRegistry,
  createSupportRagToolRegistry,
  type HumanEscalationHandler,
  type HumanEscalationInput,
  type HumanEscalationOutput,
  type SupportDraftHandler,
  type SupportDraftInput,
  type SupportDraftOutput,
  type SupportRagToolRegistryOptions,
} from "./tools/profiles.js";

// Reusable agent presets and adapters
export {
  AGENT_PRESETS,
  appointmentBookingAssistantPreset,
  codingAgentPreset,
  customerSupportAssistantPreset,
  internalOpsAssistantPreset,
  publicWebsiteAssistantPreset,
  ragKnowledgeAssistantPreset,
  salesIntakeAssistantPreset,
  supportRagAssistantPreset,
  type AppointmentPresetConfig,
  type BrandPresetConfig,
  type RagPresetConfig,
  type SupportRagPresetConfig,
} from "./presets/index.js";
export {
  createHttpAssistantAdapter,
  createStreamingHttpAssistantAdapter,
  createWhatsAppAssistantAdapter,
  createWebhookAssistantAdapter,
  type ChannelAdapter,
  type ChannelInput,
  type ChannelOutput,
  type HttpAssistantAdapter,
  type StreamingHttpAssistantAdapter,
  type WhatsAppAssistantAdapter,
  type WhatsAppInboundMessage,
} from "./adapters/index.js";

// Utilities
export { CocoError, ConfigError, PhaseError, TaskError } from "./utils/errors.js";
export { createLogger } from "./utils/logger.js";
export { installProxyDispatcher } from "./utils/proxy.js";
